downloads:
  ultimate:
    - text: "Úplná pravidla Ultimate Frisbee 2017 (cs)"
      link: assets/files/pravidla_ultimate_2017.pdf
  sotg:
    - text: "SOTG formulář"
      link: assets/files/sotg-scoring-sheet-2014.pdf
    - text: "SOTG formulář (hodnocení vlastního týmu)"
      link: assets/files/sotg-self-scoring-sheet-2014.pdf
    - text: "Návod k hodnocení"
      link: assets/files/sotg-scoring-system-2014-examples.pdf
  pravidla:
    - text: Pravidla 2017 (zip)
      link: assets/files/pravidla_ultimate_2017.zip
    - text: Doplněk pravidel pro hru v hale, 2017
      link: assets/files/pravidla_haloveho_ultimate_2017.zip
  jak-zacit:
    - text: Oddílová přihláška do ČAU
      link: assets/files/oddilova_prihlaska_cau.pdf
  poradani-turnaje:
    - text: "HOWTO: organize ČAU turnaje"
    - text: Smlouva o spolupráci (organizátor a VR)
    - text: Score sheets
    - text: SOTG formuláře

links:
  ultimate:
    - text: "Wikipedie (cs)"
      link: https://cs.wikipedia.org/wiki/Ultimate_Frisbee
    - text: "Wikipedie (en)"
      link: https://en.wikipedia.org/wiki/Ultimate_(sport)
    - text: "Pravidla na stránkách WFDF (en)"
      link: http://www.wfdf.org/sports/rules-of-play
    - text: "O ultimate na USA Ultimate (en)"
      link: https://www.usaultimate.org/about/ultimate/
  sotg:
    - text: "O SOTG na stránkách WFDF"
      link: http://www.wfdf.org/sotg/about-sotg
    - text: "O SOTG na USA Ultimate"
      link: https://www.usaultimate.org/about/ultimate/spirit_of_the_game.aspx
  historie:
    - text: "Historie na stránkách WFDF"
      link: http://www.wfdf.org/history-stats/history-of-ultimate
  reprezentace-vysledky:
    - text: "Archiv výsledků národních týmů"
      link: http://hartti.com/national_teams/index.php
  evropska-liga:
    - text: European ultimate championships series (EUCS) na stránkach EUF
      link: https://www.ultimatefederation.eu/club-champs.php
  pravidla:
    - text: Veškeré soubory k pravidlum od WFDF
      link: http://www.wfdf.org/sports/rules-of-play
    - text: Web WFDF věnovaný čistě jen pravidlům a jejich interpretacím
      link: https://rules.wfdf.org/
  jak-zacit:
    - text: Frisbee e-shop Ultimo
      link: https://www.ultimo.cz/
  worlds:
    - text: Hot Beaches skončily na mistrovství světa v ultimate frisbee na vynikajícím 12. místě (sport.cz, 2010)
      link: https://www.sport.cz/ostatni/frisbee/clanek/171983-hot-beaches-skoncily-na-mistrovstvi-sveta-v-ultimate-frisbee-na-vynikajicim-12-miste.html#section-artcl
  plazove-turnaje:
    - text: Čeští junioři ovládli prestižní turnaj v Rimini (sport.cz, 2011)
      link: https://www.sport.cz/ostatni/frisbee/clanek/185621-cesti-juniori-ovladli-prestizni-turnaj-v-rimini.html
  vysledky:
    - text: Detailní výsledky turnajů (frisbee.cz)
      link: http://www.frisbee.cz/online-vysledky.html

contact:
  ssl:
    name: "Tomáš Toušek"
    phone: "731 612 805"
    email: tomas.tousek@czechultimate.com
  minigranty:
    email: rozvoj@czechultimate.cz
  nabidka-asociace:
    email: rozvoj@czechultimate.cz
  skoleni-ucitelu:
    email: rozvoj@czechultimate.cz
  jak-zacit:
    email: info@czechultimate.cz
